#ifndef CRESSIM_NEO_GRAPHICS_HOST_SCENE_H
#define CRESSIM_NEO_GRAPHICS_HOST_SCENE_H

#include "common/id.h"
#include "common/math_types.h"
#include "gpu/gpu_types.h"
#include "graphics/gpu_scene.h"
#include "graphics/passes/forward_draw_types.h"
#include "graphics/render_resource_manager.h"

#include <vector>

/// @file host_scene.h
/// @brief Host CPU scene graph data structures, camera views, light sources, and renderable instance records.

namespace cressim::neo::graphics
{

/// @brief Clear behavior and background mode applied prior to rendering a camera's view.
enum class CameraBackgroundMode : std::uint32_t
{
    ClearColor         = 0u, ///< Clear to solid RGBA color.
    EnvironmentCubemap = 1u, ///< Render background skybox cubemap.
};

/// @brief Host representation of a renderable mesh entity placed in an environment.
struct RenderableInstance
{
    common::EntityId entityId    = common::kInvalidEntityId; ///< Entity identifier in scene graph.
    std::uint32_t envIndex       = 0u;                       ///< Zero-based environment index.
    std::uint32_t objectSlot     = 0xffffffffu;              ///< Slot index within the environment's object array.
    bool visible                 = true;                     ///< Visibility toggle flag.
    std::uint32_t segmentationId = 0u;                       ///< Categorical integer ID for segmentation mask rendering.
    common::Transform worldTransform{};                      ///< World-space 3D transform.
    MeshHandle mesh{};                                       ///< Bound geometry mesh handle.
    MaterialHandle material{};                               ///< Bound surface material handle.
};

/// @brief Host representation of a virtual camera sensor.
struct CameraData
{
    /// @brief Target render product generated by this camera.
    enum class Product : std::uint32_t
    {
        ColorDepth        = 0u, ///< Standard RGB color buffer and linear depth.
        Depth             = 1u, ///< High-precision depth buffer only.
        SegmentationDepth = 2u, ///< Integer class segmentation mask and linear depth.
    };

    common::EntityId entityId = common::kInvalidEntityId; ///< Camera entity ID.
    std::uint32_t envIndex    = 0u;                       ///< Environment index hosting the camera.
    std::uint32_t cameraSlot  = 0xffffffffu;              ///< Camera index within the environment.
    common::Transform worldTransform{};                   ///< Camera world-space eye pose.
    float verticalFovDegrees = 60.0f;                     ///< Vertical field of view in degrees.
    float nearClip           = 0.01f;                     ///< Near clipping plane distance.
    float farClip            = 1000.0f;                   ///< Far clipping plane distance.
    Product product          = Product::ColorDepth;       ///< Output product type.

    gpu::RenderOutputBinding output{};                    ///< Output surface destination binding.
    std::uint32_t outputWidth  = 0;                       ///< Target width in pixels (0 uses destination size).
    std::uint32_t outputHeight = 0;                       ///< Target height in pixels (0 uses destination size).
    gpu::GpuRenderViewport viewport{};                    ///< Normalized subregion viewport.
    bool clearColor = true;                               ///< Clear color attachment flag.
    bool clearDepth = true;                               ///< Clear depth attachment flag.
    Diligent::float4 clearColorValue{0.0f, 0.0f, 0.0f, 1.0f}; ///< Clear color value.
    float clearDepthValue               = 1.0f;           ///< Clear depth value.
    CameraBackgroundMode backgroundMode = CameraBackgroundMode::ClearColor; ///< Background skybox mode.

    std::uint32_t renderOrder = 0;                        ///< Scheduling order for cameras drawing to shared targets.
};

/// @brief Host representation of a directional, spot, or point light source.
struct LightData
{
    common::EntityId entityId = common::kInvalidEntityId; ///< Light entity ID.
    std::uint32_t envIndex    = 0u;                       ///< Environment index hosting the light.
    std::uint32_t lightSlot   = 0xffffffffu;              ///< Light slot index within the environment.
    GpuLightType type         = GpuLightType::Directional;///< Light source type.
    Diligent::float3 position{0.0f, 0.0f, 0.0f};          ///< World position (for spot and point lights).
    Diligent::float3 direction{0.0f, -1.0f, 0.0f};        ///< World emission direction.
    Diligent::float3 color{1.0f, 1.0f, 1.0f};             ///< Linear RGB radiant flux color.
    float intensity          = 1.0f;                      ///< Radiant intensity multiplier (Lux or Lumens).
    float range              = 0.0f;                      ///< Maximum attenuation distance (0 = infinite).
    float innerConeAngle     = 0.0f;                      ///< Spotlight inner cone angle in radians.
    float outerConeAngle     = 0.0f;                      ///< Spotlight outer cone falloff angle in radians.
    float shadowDistance     = 80.0f;                     ///< Maximum shadow projection distance.
    float shadowFadeDistance = 20.0f;                     ///< Distance over which shadows fade out smoothly.
    float shadowBias         = 0.0015f;                   ///< Constant shadow depth bias.
    bool castsShadows        = true;                      ///< Whether light projects shadow maps.
};

/// @brief Immutable view bundle referencing host scene instances, cameras, lights, and draw registries for a frame.
struct HostSceneView
{
    const std::vector<RenderableInstance> *renderables                       = nullptr; ///< Array of all renderable instances.
    const std::vector<GpuRenderableMetadata> *renderableMetadata             = nullptr; ///< Per-renderable GPU metadata flags.
    const std::vector<CameraData> *cameras                                   = nullptr; ///< Array of active scene cameras.
    const std::vector<LightData> *lights                                     = nullptr; ///< Array of active scene lights.
    const std::vector<EnvironmentIblDesc> *environmentIbls                   = nullptr; ///< Per-environment IBL skybox descriptors.
    const std::vector<EnvironmentFluidDesc> *environmentFluids               = nullptr; ///< Per-environment fluid rendering settings.
    const std::vector<IndirectCommandRegistryEntry> *opaqueDrawRegistry      = nullptr; ///< Indirect draw commands for opaque pass.
    const std::vector<TransparentDrawEntry> *transparentDrawRegistry         = nullptr; ///< Sorted commands for transparent pass.
    const std::vector<IndirectCommandRegistryEntry> *shadowDrawRegistry      = nullptr; ///< Indirect draw commands for directional shadows.
    const std::vector<IndirectCommandRegistryEntry> *localShadowDrawRegistry = nullptr; ///< Indirect draw commands for local light shadows.
    const GpuEntitySceneView *gpuEntityScene                                 = nullptr; ///< GPU buffer view bindings.
};

} // namespace cressim::neo::graphics

#endif // CRESSIM_NEO_GRAPHICS_HOST_SCENE_H
